package protocol

const (
	BYTE_OF_ERROR_CODE = 2
)

const (
	ERROR_CODE_NONE                         = 1
	ERROR_CODE_INVALID_REQUEST              = 1001
	ERROR_CODE_FAIL_LOGIN                   = 2001
	ERROR_CODE_FAIL_JOIN                    = 2002
	ERROR_CODE_MYSQL_ERROR                  = 2003
	ERROR_CODE_FAIL_CREATE_NEW_CHATROOM     = 2004
	ERROR_CODE_FAIL_VIEW_AVAILABLE_CHATROOM = 2005
	ERROR_CODE_FAIL_VIEW_USER_JOIN_CHATROOM = 2006
	ERROR_CODE_FAIL_TRANSFER_MESSAGE        = 2007
)
