package protocol

const (
	PACKET_ID_LOGIN_REQ = 701
	PACKET_ID_LOGIN_RES = 702
	PACKET_ID_JOIN_REQ  = 703
	PACKET_ID_JOIN_RES  = 704
	PACKET_ID_PING_REQ  = 705
	PACKET_ID_PING_RES  = 706
)

const (
	PACKET_CREATE_NEW_CHATROOM_REQ     = 801
	PACKET_CREATE_NEW_CHATROOM_RES     = 802
	PACKET_VIEW_AVAILABLE_CHATROOM_REQ = 803
	PACKET_VIEW_AVAILABLE_CHATROOM_RES = 804
	PACKET_VIEW_USER_JOIN_CHATROOM_REQ = 805
	PACKET_VIEW_USER_JOIN_CHATROOM_RES = 806
	PACKET_CONN_AVAILABLE_CHATROOM_REQ = 807
	PACKET_CONN_AVAILABLE_CHATROOM_RES = 808
	PACKET_CONN_USER_JOIN_CHATROOM_REQ = 809
	PACKET_CONN_USER_JOIN_CHATROOM_RES = 810
	PACKET_TRANSFER_MESSAGE_REQ        = 811
	PACKET_TRANSFER_MESSAGE_RES        = 812
	PACKET_BROADCAST_MESSAGE           = 813
	PACKET_RENEW_CHATLOG_REQ           = 814
	PACKET_RENEW_CHATLOG_RES           = 815
)

const (
	PING = 1
	PONG = 8
)
